### ISSUE TITLE
Discover and implement a way to seed and manage permissions properly

### ISSUE THREAD

**Issue by v-stamenova** [HZ-HBO-ICT/it-conference#406]
To implement this, we need to:

- [x] Decide on a naming convention for permissions (i.e. "edit article", "edit-article" or "article-edit")
- [x] Design an xml/json/yaml/csv-like format that defines all the roles and permissions for the app, which can be version controlled by Git OR decide if we are creating a roles and permissions config php file in the `/config` folder
- [x] Implement an artisan command (i.e. `php artisan permissions:upsert`) that synchronizes the roles and permissions in the database with the definition files

**Edit:**
We need to change the term 'upsert' into 'synchronize'. This because upsert will either insert new or update exiting items and does NOT delete items that shouldn't be in the database anymore.

**Comment by dwaard** [comment]
For the naming convention, different examples can be found. It appears to be personal preference. Considerations might be:

- Sorting order ("article-destroy" has a more logical sorting order)
- Expressiveness ("`@can("edit-article", $atricle)`") is more expressive

**Comment by dwaard** [comment]
For the admin command, I suggest to merge this into the `UpsertMasterData.php` command

**Comment by dwaard** [comment]
UPDATE: adding more config features, like atomic and resource permissions:
```
permissions:
  like-page: [editor, user] # an atomic permission
  launch-nuke: [admin] # another atomic permission
  # Next are nested permissions. These are grouped per resource and action.
  article:
    create: [admin, editor] # These roles are defined as an array
    update:
      # These roles are defined as a sequence
      - admin
      - editor
    destroy:
      - admin
```
